exports.queries = {
	// ... existing queries ...

	getListCodeByPhone_query: (phone) => `
		SELECT 
			LISTA_CODI   
		FROM CLIENTES 
		WHERE CELULAR = '${phone}' 
	`,
	getListCodeById_query: (id) => `
  SELECT 
    LISTA_CODI  
  FROM CLIENTES 
  WHERE NUM_CLIENTE = '${id}' 
`,
	getDiscountByClientNumber_query: (clientNumber) =>
		`EXEC renova_clien_descuen_consul ${clientNumber}
`,
};

//{
//  "NUM_CLIENTE": 2134,
//  "RAZON": "Heman",
//  "DOMICILIO": "domicilio test",
//  "TELEFONO": "1165106333",
//  "FAX": "",
//  "CP": "",
//  "LOCALIDAD": "CABA",
//  "IVA": "4",
//  "CONTACTO": "",
//  "CUIT": "20323189839",
//  "CALIF": "",
//  "SALDO": null,
//  "PROVINCIA": "CF",
//  "MAIL": "ihourquescos@gmail.com ; renovafiltros@gmail.com",
//  "CODI_VENDE": "",
//  "CODI_TRANSPOR": 0,
//  "CUENTA": null,
//  "ESTADO": "A",
//  "IMPOR_LIMI_CREDI": 100000,
//  "CANTI_DIAS_VENCI": null,
//  "LUGAR_ENTREGA": null,
//  "CONTACTO_PAGO": null,
//  "LUGAR_PAGO": null,
//  "TELE_PAGO": null,
//  "OBSER_PAGO": null,
//  "LISTA_CODI": "0",
//  "PORCEN_DESCUEN": 0,
//  "FECHA_ALTA": "2018-11-15T00:00:00.000Z",
//  "DOC_PATH": "",
//  "AGRU_1": "",
//  "AGRU_2": "",
//  "AGRU_3": "",
//  "CODI_ORI": null,
//  "CTA_CTE_POR_TOTAL": "N",
//  "CONDI_VENTA": "15",
//  "NOM_FANTASIA": "Jimancio fantasia",
//  "INGRE_BRUTOS": "",
//  "PORCEN_RECARGO": 0,
//  "CODI_ANTE": "",
//  "OBSER_2": "",
//  "PORCEN_COMI": 0,
//  "WEB": null,
//  "CODI_COBRA": "",
//  "POTENCIAL": "N",
//  "PORCEN_COMI_COBRO": 0,
//  "EXEN_PERCEP_IB": null,
//  "EXEN_PERCEP_IVA": "N",
//  "EXEN_PERCEP_GCIA": "N",
//  "OBSER_ESTADO": null,
//  "COD_COMP": "FEA",
//  "PERCEP_IB_PORCEN": null,
//  "PORCEN_GANAN": 0,
//  "EXCLU_COMI_ARTI": "N",
//  "CODI_TARJE": null,
//  "TARJETA_NUME": null,
//  "CELULAR": null,
//  "DIA_CUMPLE": 0,
//  "MES_CUMPLE": 0,
//  "OBSER_DATOS_LABO": null,
//  "OBSER_GARANTES": null,
//  "OBSER_DOCUMENTACION": null,
//  "CODI_PAIS": "",
//  "GLN": "SOLO FRAMMMMM!!!!",
//  "LIMI_CODI": "",
//  "MAIL_AUTO": "S",
//  "DIA_VISITA": null,
//  "FECHA_MODI": "2025-05-06T17:07:45.000Z",
//  "USER_MODI": "rnv_admin",
//  "USER_ALTA": "gigi",
//  "MONE_PEDI_DEFAULT": "PES",
//  "FECHA_INTE": "2025-05-06T17:07:54.360Z",
//  "CODI_TABLA_GALENOS": null,
//  "LIMI_CREDI_DIAS": 1,
//  "FECHA_VENCI_TARJE": null,
//  "TIPO_DOC": null,
//  "NUM_DOC": null,
//  "COD_SUB_CATE_IVA": null,
//  "PASS_WEB": "9875",
//  "RUTEO_EJE_X": null,
//  "RUTEO_EJE_Y": null,
//  "USUARIO_WEB": "C2134",
//  "ORDEN_DE_VISITA": 0,
//  "CONDI_VENTA_MAX": "30",
//  "NRO_CUENTA_PROVEEDOR": null,
//  "CODIGO_ACTIVIA": null,
//  "CODI_ZONA": null,
//  "CODI_VENDE_RESPON": null,
//  "PORCEN_MARGEN_MIN": 0,
//  "DIAS_FRECUENCIA_CONTACTO": 0,
//  "ANIO_NAC": null,
//  "FECHA_VENCI_PASSWORD": null
//}
